language: cpp
sudo: false
env:
- export NODE_VERSION="5"
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_94a7a972b13d_key -iv $encrypted_94a7a972b13d_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- git submodule update --init --recursive
- git clone https://github.com/creationix/nvm.git ./.nvm
- source ./.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm config set python `which python`
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CC="gcc-4.8"; export CXX="g++-4.8";
  export LINK="gcc-4.8"; export LINKXX="g++-4.8"; fi
- gcc --version
- g++ --version
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- git config --global user.email "info@wanderlandtravelers.com"
- git config --global user.name "Wanderland Travelers"
- git remote remove origin
- git remote add origin git@github.com:WanderlandTravelers/wanderlandtravelers.github.io.git
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
script:
- npm install
- npm run lint
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: develop
